dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py install

script: pytest

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
